modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/petrolpark/Destroy/issues"
license="All Rights Reserved"

[[mods]]
modId="destroy"
version="${file.jarVersion}"
displayName="Destroy"
#updateJSONURL=""
displayURL="https://www.modrinth.com/mods/destroy"
logoFile="logo.png"
#credits=""
authors="petrolpark"
description='''A destructive chemistry-based add-on to Create.'''

[[dependencies.destroy]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.destroy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.destroy]]
	modId="create"
	mandatory=true
	versionRange="[0.5.1.e,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.destroy]]
	modId="petrolpark"
	mandatory=true
	versionRange="[1.0.3,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.tfmg]]
	modId="tfmg"
	mandatory=false
	ordering="AFTER"
	side="BOTH"

[[dependencies.createbigcannons]]
    modId="createbigcannons"
    mandatory=false
    versionRange="[5.5.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.curios]]
    modId="curios"
    mandatory=false
    versionRange="[5.9.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.jei]]
    modId="jei"
    mandatory=false
    versionRange="[15.12.3.55,)"
    ordering="AFTER"
    side="CLIENT"



